### ISSUE TITLE
Lua Integration

### ISSUE THREAD

**Issue by v3n** [v3n/altertum#5]
Integrate LuaJIT for game scripting purposes. 
- [x] Lua environment
- [ ] Lua resource manager (blocked by #7)
- [ ] Lua lightdata method bindings
- [ ] Port bgfx example to lua game loop
